### ISSUE TITLE
How To Learn & Contribute ToplingDB

### ISSUE THREAD

**Issue by EAHITechnology** [topling/toplingdb#7]
Hi everyone~
Is there any roadmap for toplingdb now? I'm interested in toplingdb and want to see what I can do. thx~

**Comment by rockeet** [comment]
## To Learning ToplingDB
See [rockside wiki](https://github.com/topling/rockside/wiki)

## To Using ToplingDB
See [Quick Start](https://github.com/topling/rockside/wiki/101)

## To Contribute ToplingDB
This needs more efforts, the basic contribution is to [file issues](https://github.com/topling/toplingdb/issues/new) for ToplingDB.

ToplingDB reused RocksDB unit tests:
```bash
make -j`nproc` check DEBUG_LEVEL=2
```
Now ToplingDB has two known failed rocksdb tests, but they are no harm to ToplingDB.

## Roadmap
ToplingDB has ambitious goals, now ToplingDB has outperformed RocksDB at almost all aspects.

Some people like ToplingDB's observability([webview](https://github.com/topling/rockside/wiki/WebView) & [grafana](https://github.com/topling/rockside/wiki/grafana%E5%B1%95%E7%A4%BAtoplingdb%E8%BF%90%E8%A1%8C%E6%8C%87%E6%A0%87-%E6%89%8B%E5%8A%A8%E9%85%8D%E7%BD%AE-%E5%9F%BA%E7%A1%80))

Some people like ToplingDB's [performance components](https://github.com/topling/toplingdb#toplingdb-components).

We also have many long term plans:
1. [Omit-L0-Flush](https://github.com/topling/toplingdb/wiki/Omit-L0-Flush)
1. Conditional exclude User Level Timestamp([sample code change](https://github.com/topling/toplingdb/blob/d54eb03b9cd4ef6a2ebb946cdc4cda5f91f7e119/db/db_impl/db_impl.cc#L1901-L1923))
   * This just has a minor improvements, but the code change is trivial and this is an easy start
   * This is a shotgun change, relevant code are every where
1. Some existing issues, such as: #8
1. Secondary instance for Transaction DB, we have an [in progress working branch](https://github.com/topling/toplingdb/tree/sideplugin-7.01.0-a5e51305-txn-secondary), but it is not fully tested
1. Continuous improvements
1. Well documentation

**Comment by EAHITechnology** [comment]
thx! Let me find out. If there is something i don't understand, I'll "bother" you again~

**Comment by rockeet** [comment]
> thx! Let me find out. If there is something i don't understand, I'll "bother" you again~

You are welcome!
