### ISSUE TITLE
set level0_file_num_compaction_trigger=-1  should disable intra L0 compaction

### ISSUE THREAD

**Issue by rockeet** [topling/toplingdb#8]
### Expected behavior
set `level0_file_num_compaction_trigger=-1`  should disable intra L0 compaction

### Actual behavior
set `level0_file_num_compaction_trigger=-1`  triggers infinite write stop

### Steps to reproduce the behavior
set write_buffer_size=1G and target_file_size_base=1M, then write data to DB.

---
RocksDB will schedule intra L0 compaction in some cases, now ToplingDB regards `level0_file_num_compaction_trigger=-1` for flag of  Disable intra L0 compactions, but it triggers this infinite write stop.

**Comment by EAHITechnology** [comment]
Can you assign me this issues? Maybe I want to try to solve this issue.

**Comment by rockeet** [comment]
> Can you assign me this issues? Maybe I want to try to solve this issue.

Very thanks for your contribution!

**Comment by EAHITechnology** [comment]
Why do I git clone the files of the private repository when I compile the project?

**Comment by EAHITechnology** [comment]
```
+ git clone git@github.com:topling/cspp-memtable
Cloning into 'cspp-memtable'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
+ cd sideplugin
+ git clone git@github.com:topling/cspp-wbwi
Cloning into 'cspp-wbwi'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Comment by rockeet** [comment]
1. This error does not affect whole ToplingDB.
2. Import your `rsa pubkey` to github, the `clone` will success.

**Comment by rockeet** [comment]
You can file an issue about the clone fail, I can change the `git@` to `https://` in Makefile.

**Comment by EAHITechnology** [comment]
> You can file an issue about the clone fail, I can change the `git@` to `https://` in Makefile.

ok! thx~

**Comment by EAHITechnology** [comment]
When I compiled my demo, I found that you imported `port/likely.h`, and at the same time I also found that the dependency on `port/likely.h` has been removed from rocksdb. This dependency leads to the need to add another search path, such as issues `https://github.com/facebook/rocksdb/issues/2008`. So is this behavior what we expected?

**Comment by rockeet** [comment]
Now ToplingDB will disable Intra L0 compaction if `max_level1_subcompactions > 1`, see commit a6a79feaac4d9d0998ec5bc1d68b8f194f6c0f20
> ToplingDB had added `TableFactory::AllowIntraL0Compaction()` for this purpose, then we realized using `max_level1_subcompactions > 1` is more sensible, and it just needs few code changes.
